# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2021_09_01_182438) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "audits", force: :cascade do |t|
    t.integer "auditable_id"
    t.string "auditable_type"
    t.integer "associated_id"
    t.string "associated_type"
    t.integer "user_id"
    t.string "user_type"
    t.string "username"
    t.string "action"
    t.text "audited_changes"
    t.integer "version", default: 0
    t.string "comment"
    t.string "remote_address"
    t.string "request_uuid"
    t.datetime "created_at"
    t.index ["associated_type", "associated_id"], name: "associated_index"
    t.index ["auditable_type", "auditable_id", "version"], name: "auditable_index"
    t.index ["created_at"], name: "index_audits_on_created_at"
    t.index ["request_uuid"], name: "index_audits_on_request_uuid"
    t.index ["user_id", "user_type"], name: "user_index"
  end

  create_table "cargos", force: :cascade do |t|
    t.string "descricao"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.datetime "deleted_at"
    t.text "tipo_cargo"
    t.index ["deleted_at"], name: "index_cargos_on_deleted_at"
  end

  create_table "configuracaos", force: :cascade do |t|
    t.date "data_termino_selecao"
    t.boolean "status"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.date "data_termino_recurso"
    t.date "data_inicio_recurso"
    t.date "data_inicio_selecao"
    t.date "data_inicio_recurso_pontuacao"
    t.date "data_termino_recurso_pontuacao"
    t.date "data_inicio_selecao_lideranca"
    t.date "data_termino_selecao_lideranca"
    t.date "data_inicio_recurso_lideranca"
    t.date "data_termino_recurso_lideranca"
    t.date "data_inicio_entrevista_lideranca"
    t.date "data_termino_entrevista_lideranca"
    t.date "data_apresetacao_dados_lideranca"
  end

  create_table "inscricao_liderancas", force: :cascade do |t|
    t.string "cpf"
    t.string "nome_completo"
    t.string "naturalidade"
    t.string "nacionalidade"
    t.boolean "pessoa_com_deficiencia"
    t.string "nome_mae"
    t.string "sexo"
    t.string "estado_civil"
    t.date "data_nascimento"
    t.string "rg"
    t.string "orgao_emissor"
    t.string "endereco"
    t.string "complemento"
    t.string "bairro"
    t.string "cidade"
    t.string "uf"
    t.string "cep"
    t.string "telefone_fixo"
    t.string "telefone_celular"
    t.string "email"
    t.string "orgao_representacao_classe"
    t.string "numero_registro"
    t.boolean "termo_aceito"
    t.boolean "recurso_solicitado"
    t.json "recurso"
    t.json "documentos"
    t.boolean "finalizar"
    t.boolean "deficiente"
    t.json "deficiente_anexo"
    t.boolean "correcao"
    t.text "slug"
    t.string "status_acompanhamento"
    t.integer "usuario_corrigiu_dados"
    t.text "observacao"
    t.json "represetacao_classe"
    t.boolean "cota_negro"
    t.text "recurso_candidato_dados"
    t.text "resposta_recurso_candidato_dados"
    t.boolean "reclassificar_recurso_candidato_dados"
    t.text "recurso_entrevista"
    t.text "resposta_recurso_entrevista"
    t.boolean "reclassificar_recurso_entrevista"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "ativo", default: true
    t.datetime "deleted_at"
    t.bigint "cargo_id"
    t.json "certificado_ensino_medio"
    t.json "certificado_ensino_superior"
    t.decimal "formacao_academica_01_candidato"
    t.decimal "formacao_academica_01_correcao"
    t.decimal "formacao_academica_02_candidato"
    t.decimal "formacao_academica_02_correcao"
    t.decimal "formacao_academica_03_candidato"
    t.decimal "formacao_academica_03_correcao"
    t.decimal "formacao_academica_04_candidato"
    t.decimal "formacao_academica_04_correcao"
    t.decimal "formacao_academica_05_candidato"
    t.decimal "formacao_academica_05_correcao"
    t.decimal "experiencia_profissional_01_candidato"
    t.decimal "experiencia_profissional_01_correcao"
    t.decimal "experiencia_profissional_02_candidato"
    t.decimal "experiencia_profissional_02_correcao"
    t.decimal "experiencia_profissional_03_candidato"
    t.decimal "experiencia_profissional_03_correcao"
    t.json "formacao_academica_01_file"
    t.json "formacao_academica_02_file"
    t.json "formacao_academica_03_file"
    t.json "formacao_academica_04_file"
    t.json "formacao_academica_05_file"
    t.json "experiencia_profissional_01_file"
    t.json "experiencia_profissional_02_file"
    t.json "experiencia_profissional_03_file"
    t.decimal "formacao_academica_total"
    t.decimal "experiencia_profissional_total"
    t.decimal "formacao_academica_soma_candidato"
    t.decimal "experiencia_profissional_soma_candidato"
    t.decimal "formacao_academica_soma_correcao"
    t.decimal "experiencia_profissional_soma_correcao"
    t.boolean "formacao_academica_01_verificar"
    t.boolean "formacao_academica_02_verificar"
    t.boolean "formacao_academica_03_verificar"
    t.boolean "formacao_academica_04_verificar"
    t.boolean "formacao_academica_05_verificar"
    t.boolean "experiencia_profissional_01_verificar"
    t.boolean "experiencia_profissional_02_verificar"
    t.boolean "experiencia_profissional_03_verificar"
    t.text "formacao_academica_01_obs"
    t.text "formacao_academica_02_obs"
    t.text "formacao_academica_03_obs"
    t.text "formacao_academica_04_obs"
    t.text "formacao_academica_05_obs"
    t.text "experiencia_profissional_01_obs"
    t.text "experiencia_profissional_02_obs"
    t.text "experiencia_profissional_03_obs"
    t.decimal "total_geral_candidato"
    t.decimal "total_geral_correcao"
    t.integer "formacao_academica_01_resposta"
    t.integer "formacao_academica_02_resposta"
    t.integer "formacao_academica_03_resposta"
    t.integer "formacao_academica_04_resposta"
    t.integer "formacao_academica_05_resposta"
    t.integer "experiencia_profissional_01_resposta"
    t.integer "experiencia_profissional_02_resposta"
    t.integer "experiencia_profissional_03_resposta"
    t.integer "usuario_corrigiu_entrevista"
    t.decimal "avaliacao_entrevista_01"
    t.decimal "avaliacao_entrevista_02"
    t.decimal "avaliacao_entrevista_03"
    t.decimal "avaliacao_entrevista_04"
    t.decimal "avaliacao_entrevista_05"
    t.string "avaliacao_entrevista_obs"
    t.integer "usuario_corrigiu_pontuacao"
    t.decimal "soma_total"
    t.index ["cargo_id"], name: "index_inscricao_liderancas_on_cargo_id"
    t.index ["deleted_at"], name: "index_inscricao_liderancas_on_deleted_at"
  end

  create_table "inscricao_servidors", force: :cascade do |t|
    t.string "cpf"
    t.string "nome_completo"
    t.string "naturalidade"
    t.string "nacionalidade"
    t.boolean "pessoa_com_deficiencia"
    t.string "nome_mae"
    t.string "sexo"
    t.string "estado_civil"
    t.date "data_nascimento"
    t.string "rg"
    t.string "orgao_emissor"
    t.string "endereco"
    t.string "complemento"
    t.string "bairro"
    t.string "cidade"
    t.string "uf"
    t.string "cep"
    t.string "telefone_fixo"
    t.string "telefone_celular"
    t.string "email"
    t.string "orgao_representacao_classe"
    t.string "numero_registro"
    t.boolean "termo_aceito"
    t.boolean "recurso_solicitado"
    t.json "recurso"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "ativo", default: true
    t.json "documentos"
    t.boolean "finalizar"
    t.boolean "deficiente"
    t.json "deficiente_anexo"
    t.boolean "correcao"
    t.text "slug"
    t.string "status_acompanhamento"
    t.integer "usuario_corrigiu_dados"
    t.integer "usuario_corrigiu_pontuacao"
    t.text "observacao"
    t.bigint "cargo_id"
    t.json "certificado_ensino_medio"
    t.json "certificado_ensino_superior"
    t.decimal "formacao_academica_01_candidato"
    t.decimal "formacao_academica_01_correcao"
    t.decimal "formacao_academica_02_candidato"
    t.decimal "formacao_academica_02_correcao"
    t.decimal "formacao_academica_03_candidato"
    t.decimal "formacao_academica_03_correcao"
    t.decimal "formacao_academica_04_candidato"
    t.decimal "formacao_academica_04_correcao"
    t.decimal "formacao_academica_05_candidato"
    t.decimal "formacao_academica_05_correcao"
    t.decimal "formacao_academica_06_candidato"
    t.decimal "formacao_academica_06_correcao"
    t.decimal "formacao_academica_07_candidato"
    t.decimal "formacao_academica_07_correcao"
    t.decimal "qualificacao_profissional_01_candidato"
    t.decimal "qualificacao_profissional_01_correcao"
    t.decimal "qualificacao_profissional_02_candidato"
    t.decimal "qualificacao_profissional_02_correcao"
    t.decimal "qualificacao_profissional_03_candidato"
    t.decimal "qualificacao_profissional_03_correcao"
    t.decimal "qualificacao_profissional_04_candidato"
    t.decimal "qualificacao_profissional_04_correcao"
    t.decimal "experiencia_profissional_01_candidato"
    t.decimal "experiencia_profissional_01_correcao"
    t.decimal "experiencia_profissional_02_candidato"
    t.decimal "experiencia_profissional_02_correcao"
    t.decimal "experiencia_profissional_03_candidato"
    t.decimal "experiencia_profissional_03_correcao"
    t.decimal "experiencia_profissional_04_candidato"
    t.decimal "experiencia_profissional_04_correcao"
    t.decimal "experiencia_profissional_05_candidato"
    t.decimal "experiencia_profissional_05_correcao"
    t.json "formacao_academica_01_file"
    t.json "formacao_academica_02_file"
    t.json "formacao_academica_03_file"
    t.json "formacao_academica_04_file"
    t.json "formacao_academica_05_file"
    t.json "formacao_academica_06_file"
    t.json "formacao_academica_07_file"
    t.json "qualificacao_profissional_01_file"
    t.json "qualificacao_profissional_02_file"
    t.json "qualificacao_profissional_03_file"
    t.json "qualificacao_profissional_04_file"
    t.json "experiencia_profissional_01_file"
    t.json "experiencia_profissional_02_file"
    t.json "experiencia_profissional_03_file"
    t.json "experiencia_profissional_04_file"
    t.json "experiencia_profissional_05_file"
    t.decimal "formacao_academica_total"
    t.decimal "qualificacao_profissional_total"
    t.decimal "experiencia_profissional_total"
    t.decimal "formacao_academica_soma_candidato"
    t.decimal "qualificacao_profissional_soma_candidato"
    t.decimal "experiencia_profissional_soma_candidato"
    t.decimal "formacao_academica_soma_correcao"
    t.decimal "qualificacao_profissional_soma_correcao"
    t.decimal "experiencia_profissional_soma_correcao"
    t.boolean "formacao_academica_01_verificar"
    t.boolean "formacao_academica_02_verificar"
    t.boolean "formacao_academica_03_verificar"
    t.boolean "formacao_academica_04_verificar"
    t.boolean "formacao_academica_05_verificar"
    t.boolean "formacao_academica_06_verificar"
    t.boolean "formacao_academica_07_verificar"
    t.boolean "qualificacao_profissional_01_verificar"
    t.boolean "qualificacao_profissional_02_verificar"
    t.boolean "qualificacao_profissional_03_verificar"
    t.boolean "qualificacao_profissional_04_verificar"
    t.boolean "experiencia_profissional_01_verificar"
    t.boolean "experiencia_profissional_02_verificar"
    t.boolean "experiencia_profissional_03_verificar"
    t.boolean "experiencia_profissional_04_verificar"
    t.boolean "experiencia_profissional_05_verificar"
    t.text "formacao_academica_01_obs"
    t.text "formacao_academica_02_obs"
    t.text "formacao_academica_03_obs"
    t.text "formacao_academica_04_obs"
    t.text "formacao_academica_05_obs"
    t.text "formacao_academica_06_obs"
    t.text "formacao_academica_07_obs"
    t.text "qualificacao_profissional_01_obs"
    t.text "qualificacao_profissional_02_obs"
    t.text "qualificacao_profissional_03_obs"
    t.text "qualificacao_profissional_04_obs"
    t.text "experiencia_profissional_01_obs"
    t.text "experiencia_profissional_02_obs"
    t.text "experiencia_profissional_03_obs"
    t.text "experiencia_profissional_04_obs"
    t.text "experiencia_profissional_05_obs"
    t.decimal "total_geral_candidato"
    t.decimal "total_geral_correcao"
    t.text "recurso_candidato"
    t.text "resposta_recurso_candidato"
    t.boolean "reclassificar_recurso_candidato"
    t.text "recurso_pontuacao"
    t.text "resposta_recurso_pontuacao"
    t.boolean "reclassificar_recurso_pontuacao"
    t.datetime "deleted_at"
    t.integer "formacao_academica_01_resposta"
    t.integer "formacao_academica_02_resposta"
    t.integer "formacao_academica_03_resposta"
    t.integer "formacao_academica_04_resposta"
    t.integer "formacao_academica_05_resposta"
    t.integer "formacao_academica_06_resposta"
    t.integer "formacao_academica_07_resposta"
    t.integer "qualificacao_profissional_01_resposta"
    t.integer "qualificacao_profissional_02_resposta"
    t.integer "qualificacao_profissional_03_resposta"
    t.integer "qualificacao_profissional_04_resposta"
    t.integer "experiencia_profissional_01_resposta"
    t.integer "experiencia_profissional_02_resposta"
    t.integer "experiencia_profissional_03_resposta"
    t.integer "experiencia_profissional_04_resposta"
    t.integer "experiencia_profissional_05_resposta"
    t.json "represetacao_classe"
    t.boolean "cota_negro"
    t.index ["cargo_id"], name: "index_inscricao_servidors_on_cargo_id"
    t.index ["deleted_at"], name: "index_inscricao_servidors_on_deleted_at"
  end

  create_table "inscricaos", force: :cascade do |t|
    t.string "nome_completo"
    t.string "naturalidade"
    t.string "nacionalidade"
    t.string "nome_mae"
    t.string "sexo"
    t.string "estado_civil"
    t.date "data_nascimento"
    t.string "cpf"
    t.string "rg"
    t.string "orgao_emissor"
    t.string "endereco"
    t.string "complemento"
    t.string "bairro"
    t.string "cidade"
    t.string "uf"
    t.string "cep"
    t.string "telefone_fixo"
    t.string "telefone_celular"
    t.string "email"
    t.string "formacao"
    t.string "orgao_representacao_classe"
    t.string "numero_registro"
    t.boolean "termo_aceito"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.json "curriculo"
    t.json "documentacao"
    t.boolean "recurso_solicitado"
    t.json "recurso"
  end

  create_table "local_contratacaos", force: :cascade do |t|
    t.string "descricao"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "recurso_servidors", force: :cascade do |t|
    t.bigint "inscricao_servidor_id"
    t.text "texto"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["inscricao_servidor_id"], name: "index_recurso_servidors_on_inscricao_servidor_id"
  end

  create_table "regiaos", force: :cascade do |t|
    t.bigint "inscricao_lideranca_id"
    t.string "descricao"
    t.integer "ordem"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.bigint "local_contratacao_id"
    t.index ["inscricao_lideranca_id"], name: "index_regiaos_on_inscricao_lideranca_id"
    t.index ["local_contratacao_id"], name: "index_regiaos_on_local_contratacao_id"
  end

  create_table "resposta", force: :cascade do |t|
    t.string "descricao"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end

  create_table "selecionar_vagas", force: :cascade do |t|
    t.bigint "inscricao_servidor_id"
    t.bigint "cargo_id"
    t.boolean "sexo"
    t.decimal "formacao_academica_01_candidato"
    t.decimal "formacao_academica_01_correcao"
    t.decimal "formacao_academica_02_candidato"
    t.decimal "formacao_academica_02_correcao"
    t.decimal "formacao_academica_03_candidato"
    t.decimal "formacao_academica_03_correcao"
    t.decimal "formacao_academica_04_candidato"
    t.decimal "formacao_academica_04_correcao"
    t.decimal "formacao_academica_05_candidato"
    t.decimal "formacao_academica_05_correcao"
    t.decimal "formacao_academica_06_candidato"
    t.decimal "formacao_academica_06_correcao"
    t.decimal "formacao_academica_07_candidato"
    t.decimal "formacao_academica_07_correcao"
    t.decimal "qualificacao_profissional_01_candidato"
    t.decimal "qualificacao_profissional_01_correcao"
    t.decimal "qualificacao_profissional_02_candidato"
    t.decimal "qualificacao_profissional_02_correcao"
    t.decimal "qualificacao_profissional_03_candidato"
    t.decimal "qualificacao_profissional_03_correcao"
    t.decimal "qualificacao_profissional_04_candidato"
    t.decimal "qualificacao_profissional_04_correcao"
    t.decimal "experiencia_profissional_01_candidato"
    t.decimal "experiencia_profissional_01_correcao"
    t.decimal "experiencia_profissional_02_candidato"
    t.decimal "experiencia_profissional_02_correcao"
    t.decimal "experiencia_profissional_03_candidato"
    t.decimal "experiencia_profissional_03_correcao"
    t.decimal "experiencia_profissional_04_candidato"
    t.decimal "experiencia_profissional_04_correcao"
    t.decimal "experiencia_profissional_05_candidato"
    t.decimal "experiencia_profissional_05_correcao"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.json "formacao_academica_01_file"
    t.json "formacao_academica_02_file"
    t.json "formacao_academica_03_file"
    t.json "formacao_academica_04_file"
    t.json "formacao_academica_05_file"
    t.json "formacao_academica_06_file"
    t.json "formacao_academica_07_file"
    t.json "qualificacao_profissional_01_file"
    t.json "qualificacao_profissional_02_file"
    t.json "qualificacao_profissional_03_file"
    t.json "qualificacao_profissional_04_file"
    t.json "experiencia_profissional_01_file"
    t.json "experiencia_profissional_02_file"
    t.json "experiencia_profissional_03_file"
    t.json "experiencia_profissional_04_file"
    t.json "experiencia_profissional_05_file"
    t.decimal "formacao_academica_total"
    t.decimal "qualificacao_profissional_total"
    t.decimal "experiencia_profissional_total"
    t.decimal "formacao_academica_soma_candidato"
    t.decimal "qualificacao_profissional_soma_candidato"
    t.decimal "experiencia_profissional_soma_candidato"
    t.decimal "formacao_academica_soma_correcao"
    t.decimal "qualificacao_profissional_soma_correcao"
    t.decimal "experiencia_profissional_soma_correcao"
    t.boolean "formacao_academica_01_verificar"
    t.boolean "formacao_academica_02_verificar"
    t.boolean "formacao_academica_03_verificar"
    t.boolean "formacao_academica_04_verificar"
    t.boolean "formacao_academica_05_verificar"
    t.boolean "formacao_academica_06_verificar"
    t.boolean "formacao_academica_07_verificar"
    t.boolean "qualificacao_profissional_01_verificar"
    t.boolean "qualificacao_profissional_02_verificar"
    t.boolean "qualificacao_profissional_03_verificar"
    t.boolean "qualificacao_profissional_04_verificar"
    t.boolean "experiencia_profissional_01_verificar"
    t.boolean "experiencia_profissional_02_verificar"
    t.boolean "experiencia_profissional_03_verificar"
    t.boolean "experiencia_profissional_04_verificar"
    t.boolean "experiencia_profissional_05_verificar"
    t.text "formacao_academica_01_obs"
    t.text "formacao_academica_02_obs"
    t.text "formacao_academica_03_obs"
    t.text "formacao_academica_04_obs"
    t.text "formacao_academica_05_obs"
    t.text "formacao_academica_06_obs"
    t.text "formacao_academica_07_obs"
    t.text "qualificacao_profissional_01_obs"
    t.text "qualificacao_profissional_02_obs"
    t.text "qualificacao_profissional_03_obs"
    t.text "qualificacao_profissional_04_obs"
    t.text "experiencia_profissional_01_obs"
    t.text "experiencia_profissional_02_obs"
    t.text "experiencia_profissional_03_obs"
    t.text "experiencia_profissional_04_obs"
    t.text "experiencia_profissional_05_obs"
    t.decimal "total_geral_candidato"
    t.decimal "total_geral_correcao"
    t.index ["cargo_id"], name: "index_selecionar_vagas_on_cargo_id"
    t.index ["inscricao_servidor_id"], name: "index_selecionar_vagas_on_inscricao_servidor_id"
  end

  create_table "usuarios", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_usuarios_on_email", unique: true
    t.index ["reset_password_token"], name: "index_usuarios_on_reset_password_token", unique: true
  end

  add_foreign_key "inscricao_liderancas", "cargos"
  add_foreign_key "inscricao_servidors", "cargos"
  add_foreign_key "recurso_servidors", "inscricao_servidors"
  add_foreign_key "regiaos", "inscricao_liderancas"
  add_foreign_key "regiaos", "local_contratacaos"
  add_foreign_key "selecionar_vagas", "cargos"
  add_foreign_key "selecionar_vagas", "inscricao_servidors"
end
