class ApplicationController < ActionController::Base
  before_action :authenticate_usuario!

  def remover_acentos(str)
    str = str.strip
    str = str.gsub(/[ÀÁÂÃÄÅĀĂĄ]/, 'A')
    str = str.gsub(/[àáâãäåāăą]/, 'a')
    str = str.gsub(/[ÇĆĈĊČ]/, 'C')
    str = str.gsub(/[çćĉċč]/, 'c')
    str = str.gsub(/[ÐĎ]/, 'D')
    str = str.gsub(/[ďđ]/, 'd')
    str = str.gsub(/[ÈÉÊËĒĔĖĘĚ]/, 'E')
    str = str.gsub(/[èéêëēĕėęě]/, 'e')
    str = str.gsub(/[ĝğġģ]/, 'g')
    str = str.gsub(/[ĜĞĠĢ]/, 'G')
    str = str.gsub(/[ĥħ]/, 'h')
    str = str.gsub(/[ĤĦ]/, 'H')
    str = str.gsub(/[ìíîïĩīĭįı]/, 'i')
    str = str.gsub(/[ÌÍÎÏĨĪĬĮİ]/, 'I')
    str = str.gsub(/[Ĵ]/, 'J')
    str = str.gsub(/[ĵ]/, 'j')
    str = str.gsub(/[Ķķ]/, 'K')
    str = str.gsub(/[ĸ]/, 'k')
    str = str.gsub(/[ĺļ]/, 'l')
    str = str.gsub(/[ĹĻĽľĿŀŁł]/, 'L')
    str = str.gsub(/[ñńņňŉŋ]/, 'n')
    str = str.gsub(/[ÑŃŅŇŊ]/, 'N')
    str = str.gsub(/[ÒÓÔÕÖØŌŎŐ]/, 'O')
    str = str.gsub(/[òóôõöøōŏő]/, 'o')
    str = str.gsub(/[ŕŗř]/, 'r')
    str = str.gsub(/[ŔŖŘ]/, 'B')
    str = str.gsub(/[śŝşš]/, 's')
    str = str.gsub(/[ŚŜŞŠ]/, 'S')
    str = str.gsub(/[ſ]/, 'f')
    str = str.gsub(/[ţťŧ]/, 't')
    str = str.gsub(/[ŢŤŦ]/, 'T')
    str = str.gsub(/[ùúûüũūŭůűų]/, 'u')
    str = str.gsub(/[ÙÚÛÜŨŪŬŮŰŲ]/, 'U')
    str = str.gsub(/[Ŵ]/, 'W')
    str = str.gsub(/[ŵ]/, 'w')
    str = str.gsub(/[ýÿŷ]/, 'y')
    str = str.gsub(/[ÝŶŸ]/, 'Y')
    str = str.gsub(/[źž]/, 'z')
    str = str.gsub(/[ŹŻŽ]/, 'Z')
    str = str.gsub(/['+."!@#$%¨&*()-=]/, '')
    str = str.gsub(/^a-zA-Z0-9_/, '')
    str = str.gsub(/[(){}<>?,;:~^´`]/, '')
    str = str.gsub(/['"!@#$%¨&*+=§°º]/, '')
    str = str.gsub(/[ -]/, '_')
    str = str.gsub("[", '')
    str = str.gsub("]", '')
    str = str.gsub("__", '_')
    str = str.gsub("___", '_')
    str = str.gsub("____", '_')
    str = str.gsub("_____", '_')
  end
end
